ARG CHAIN_VERSION=latest
ARG SF_VERSION=latest

FROM staketechnologies/astar-collator:$CHAIN_VERSION as chain
FROM ghcr.io/streamingfast/firehose-astar:$SF_VERSION

COPY --from=chain /usr/local/bin/astar-collator /app/astar-collator

COPY tools/fireastar/motd_node_manager /etc/motd
COPY tools/fireastar/scripts/. /usr/local/bin/
